#!/usr/bin/env bash

# required passsed arguments
# $icon - global icon
# $title - global title
# $icons_rofi - util icons
# $icon_notify - util icons

# helps passing icons to awk
set_icon_vars() {
  for arg in "$@"; do
    echo "-v icon_$arg=${icons_rofi[$arg]:?} "
  done
}

set_message() {
  echo -en "\0message\x1f$1\n"
}

set_title() {
  echo -en "\0prompt\x1f${icon:?}  $1\n"
}

set_subtitle() {
  set_title "→   $1 $2"
}

print_divider() {
  echo -en " \0nonselectable\x1ftrue\n"
}

# TODO: pass theme icons (remove hard-coded blueman)
notify() {
  desc=$(echo "$1" | sed 's/\x1b\[[0-9;]*m//g' | sed 's/[\x01\x02]//g')
  status=${2:-0}

  [[ $status == 0 ]] && urgency=normal || urgency=critical
  notify-send "${title:?}" "$desc" -i "${icon_notify:?}" -u "$urgency"
}
