source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "alexherbo2/prelude.kak"
plug "occivink/kakoune-find"
plug "alexherbo2/search-highlighter.kak" defer search-highlighter %{
  search-highlighter-enable
} demand

plug "alexherbo2/auto-pairs.kak" defer auto-pairs %{
  auto-pairs-enable
} demand

plug "andreyorst/smarttab.kak" defer smarttab %{
  set-option global softtabstop 2
} config %{
  hook global WinSetOption filetype=.* expandtab
}

source "~/.config/kak/code.kak"
source "~/.config/kak/mappings.kak"
source "~/.config/kak/files.kak"
source "~/.config/kak/ui.kak"
source "~/.config/kak/kitty-ide.kak"
