source "%val{config}/colorscheme.kak"

# plug.kak
source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload

plug "andreyorst/smarttab.kak" defer %{
  set-option global softtabstop 2
  hook global WinSetOption .* %{ expandtab }
}

plug "andreyorst/fzf.kak" %{
  map -docstring 'fzf mode' global user f ': fzf-mode<ret>'
} demand fzf %{
  set-option global fzf_terminal_command 'kitty-terminal-overlay kak -c %val{session} -e "%arg{@}"'
  set-option global fzf_highlight_command 'bat'
} demand fzf-file %{
  set-option global fzf_file_command 'rg --files --hidden'
}

plug "andreyorst/tagbar.kak" %{
  # if you have wrap highlighter enamled in you configuration
  # files it's better to turn it off for tagbar, using this hook:
  hook global WinSetOption filetype=tagbar %{
    remove-highlighter window/wrap
    # you can also disable rendering whitespaces here, line numbers, and
    # matching characters
  }
} defer "tagbar" %{
  set-option global tagbar_sort false
  set-option global tagbar_size 40
  set-option global tagbar_display_anon false
}

plug "alexherbo2/lib.kak"

plug "alexherbo2/surround.kak" %{
  map -docstring 'surround mode' global user s ':surround<ret>'
}

plug "alexherbo2/auto-pairs.kak" %{ enable-auto-pairs }

plug "alexherbo2/word-select.kak" defer word-select %{ word-select-add-mappings }

plug "occivink/kakoune-vertical-selection" %{
  map -docstring 'vertsel down' global user v     ': vertical-selection-down<ret>'
  map -docstring 'vertsel up' global user <a-v> ': vertical-selection-up<ret>'
  map -docstring 'vertsel up/down' global user V     ': vertical-selection-up-and-down<ret>'
}

plug "occivink/kakoune-find"
plug "occivink/kakoune-sudo-write"
plug "occivink/kakoune-snippets" %{
  def -hidden insert-c-n %{
    try %{
      snippets-select-next-placeholders
      exec '<a-;>d'
    } catch %{
      exec -with-hooks '<c-n>'
    }
  }
  map global insert <a-n> "<a-;>: insert-c-n<ret>"
  map global insert <a-s> '<a-;>: snippets '
}
 
source "%val{config}/ui.kak"
source "%val{config}/files.kak"
source "%val{config}/mappings.kak"
source "%val{config}/code.kak"
source "%val{config}/kitty-ide.kak"
source "%val{config}/asterisk.kak"
source "%val{config}/toggle-highlighter.kak"
