env = MOZ_ENABLE_WAYLAND,1

## Toolkit
env = GDK_BACKEND,wayland,x11
env = SLD_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland

## XDG Specs
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland

## GTK variables
# TODO: use koppa
env = GTK_THEME,Arc-Dark

## QT Variables
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_SCALE_FACTOR,2
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
# Unirform theme for QT using qt5-styleplugins & qtgtk2
# https://wiki.archlinux.org/title/Uniform_look_for_Qt_and_GTK_applications#QGtkStyle
env = QT_QPA_PLATFORMTHEME,gtk2
