# gtk
exec = gsettings set org.gnome.desktop.interface gtk-theme '%{theme}%'
exec = gsettings set org.gnome.desktop.interface icon-theme '%{theme_icon}%'
exec = gsettings set org.gnome.desktop.interface font-name '%{font_sans}% %{font_size_sm}%'
exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

# nec = gsettings set org.nemo.desktop show-desktop-icons false
exec = gsettings set org.cinnamon.desktop.default-applications.terminal exec kitty
exec = gsettings set org.cinnamon.desktop.default-applications.terminal exec-arg --
