general {
  before_sleep_cmd = pidof hyprlock || hyprlock
  after_sleep_cmd = hyprctl dispatch dpms on
}

# 2 min: dim/restore monitor brightness and keyboard backlight, battery only.
# listener {
#   timeout = 5
#   on-timeout = sh -c '
#     if grep -qs 1 /sys/class/power_supply/AC*/online 2>/dev/null; then
#       exit 0
#     fi

#     pkill -USR1 -x wluma || true

#     cur=$(brightnessctl -p get)
#     brightnessctl -s set "$([ "$cur" -gt 10 ] && echo "10%" || echo "3%")"
#     brightnessctl -sd tpacpi::kbd_backlight set 0
#   '
#   on-resume = sh -c '
#     if grep -qs 1 /sys/class/power_supply/AC*/online 2>/dev/null; then
#       exit 0
#     fi

#     brightnessctl -r
#     brightnessctl -rd tpacpi::kbd_backlight
#     pkill -USR2 -x wluma || true
#   '
# }

# 5 min: turn off/on monitor
listener {
  timeout = 300
  on-timeout = hyprctl dispatch dpms off
  on-resume = hyprctl dispatch dpms on
}

# 20 min: lock screen
listener {
  timeout = 1200
  on-timeout = pidof hyprlock || hyprlock
}
