#!/usr/bin/env bash

icon=
title="Helix Projects"
# icon_notify=dialog-password-panel
source "$(dirname "$0")/common/utils" "$icon" "$title"

set_title "$title"

# manually managed projects
projs=~/.config/hxi.projs

# automatically scanned directory
uw2_tickets=~/Work/un/tickets
uw2_repos=~/Work/un/repos

helix_cd() {
  kitten="dispatch exec kitty -d='$1'"
  hx="$kitten -T '[$2] - hx' --hold helix"
  term1="$kitten -T '[$2] - t1'"
  term2="$kitten -T '[$2] - t2'"

  # create 3 pane window layout
  # NOTE: 0.2s is appropriate wait for dispatches to trigger once previous command completes
  coproc {
    hyprctl "$hx"
    sleep 0.2s
    hyprctl "$term1"
    sleep 0.2s
    hyprctl "dispatch togglesplit"
    sleep 0.2s
    hyprctl "$term2"
    sleep 0.2s
    hyprctl "dispatch resizeactive 0 60%"
    hyprctl "dispatch movefocus u"
  }
}

if [[ $ROFI_RETV == 0 ]]; then
  # initial list
  projs_file=$(awk -F':' '{
    printf "%s (%s)\\0info\x1f%s:%s\n", $2, $1, $1, $2
  }' <"$projs")

  projs_uw_tickets=$(fd -d1 -td 'UW2' "$uw2_tickets" |
    awk -F'/' '{
    printf "ticket: %s\\0info\x1f%s:%s\n", $(NF-1), $0, $(NF-1)
  }')

  projs_uw_base=$(fd -d1 -td -H --regex '^.uw-.+-git$' "$uw2_tickets" |
    awk -F'/' '{
    name=$(NF-1)
    name=gensub(/\.uw-/, "", "g", name)
    name=gensub(/-git/, "", "g", name)
    printf "base: %s\\0info\x1f%s:%s\n", name, $0, name
  }')

  projs_uw_repos=$(fd -d1 -td "." "$uw2_repos" |
    awk -F'/' '{
    printf "repo: %s\\0info\x1f%s:%s\n", $(NF-1), $0, $(NF-1)
  }')

  echo -en "$projs_file\n"
  print_divider
  echo -en "$projs_uw_tickets\n"
  echo -en "$projs_uw_base\n"
  echo -en "$projs_uw_repos\n"
fi

if [[ $ROFI_RETV == 1 ]]; then
  IFS=":" read -r -a data <<<"$ROFI_INFO"
  helix_cd "${data[0]}" "${data[1]}"
fi
