#!/usr/bin/env bash

icon=
title=IPTV

if [[ $ROFI_RETV == 0 ]]; then
  echo -en "\0prompt\x1f$icon $title\n"

  # parsed=$(
  #   wget -O - https://tv123.me/iptv/446515/Z7mxUVWBGm/Default 2> /dev/null | awk -F ',' '
  #       /^#EXTINF/{
  #         printf("%s;", $2)
  #         # printf "\\0info\\x1f"
  #       }
  #       /^#EXTGRP/{
  #         printf("%s;", gensub(/^#EXTGRP:(.*)/, "\\1", "g", $1))
  #       }
  #       /^http/{
  #         printf "%s\\n", $1
  #       }
  #     '
  # )
  # echo $parsed
  # echo -en $(echo -en $parsed | awk -F ';' '{ printf "[%s] %s\\0info\\x1f%s\\n", $2, $1, $3 }') > ~/.cache/rofi-iptv
  cat ~/.cache/rofi-iptv
elif [[ $ROFI_RETV == 1 ]]; then
  mpv $ROFI_INFO &> /dev/null &
  exit 0
fi
