#!/usr/bin/env bash

icon=
title=IPTV
source "$(dirname "$0")/common/utils" "$icon" "$title"
set_title "$title"

print_options() {
  echo -en "  Download & Sync\0info\x1fsync\n"
  echo -en "  Refresh\0info\x1frefresh\n"
  print_divider

  cat ~/.cache/rofi-iptv
}

if [[ $ROFI_RETV == 0 ]]; then
  print_options
elif [[ $ROFI_RETV == 1 ]]; then
  case $ROFI_INFO in
  sync)
    parsed=$(
      wget -O - https://tv123.me/iptv/446515/Z7mxUVWBGm/Default 2>/dev/null | awk -F ',' '
          /^#EXTINF/{
            printf("%s;", $2)
            # printf "\\0info\\x1f"
          }
          /^#EXTGRP/{
            printf("%s;", gensub(/^#EXTGRP:(.*)/, "\\1", "g", $1))
          }
          /^http/{
            printf "%s\\n", $1
          }
        '
    )
    echo -en "$(echo -en "$parsed" | awk -F ';' '{ printf "[%s] %s\\0info\\x1f%s\\n", $2, $1, $3 }')" >~/.cache/rofi-iptv
    exit 0
    ;;
  refresh)
    print_options
    ;;
  *)
    mpv "$ROFI_INFO" &>/dev/null &
    exit 0
    ;;
  esac
fi
