#!/usr/bin/env bash

# TODO: use notifications

icon=
title=Timezone
icon_notify=state-ok
source "$(dirname "$0")/common/utils" "$icon" "$title" "$icon_notify"

declare -A cmd
cmd[list_timezones]=list-timezones
cmd[change_timezone]=change-timezone

set_title $title

list_timezones() {
  output=$(
    timedatectl list-timezones |
      awk -v cmd="${cmd[change_timezone]}" '{
        tz=$1
        printf "%s\\0info\x1f%s:%s\n", tz, cmd, tz
      }'
  )
  echo -en "$output"
}

# FIRST RUN
if [[ $ROFI_RETV == 0 ]]; then
  list_timezones
fi

# ENTRY MADE
if [[ $ROFI_RETV == 1 ]]; then
  case $ROFI_INFO in
  "${cmd[list_timezones]}")
    list_timezones
    ;;
  "${cmd[change_timezone]}":*)
    tz=${ROFI_INFO#*"${cmd[copy]}":}
    coproc {
      timedatectl set-timezone "$tz"
      notify "Timezone Changed"
    }
    ;;
  esac
fi
