#!/usr/bin/env bash

icon=
title=uDiskie
source "$(dirname "$0")/common/utils" "$icon" "$title" "$icon_notify"

declare -A cmd
cmd[lsmounts]=list_mounts
cmd[mount]=mount
cmd[umount]=umount

set_title "$title"

list_devices() {
  echo -e "$(udiskie-info -a | awk -F': ' '/^device/ {print $2}')"
}

list_mounts() {
  udiskie-info -a | awk -F': ' '/^mount_path/ {print $2}'
}

mount_device() {
  local device=$1
  udiskie-mount "$device"
}

unmount_device() {
  local mount_point=$1
  udiskie-umount "$mount_point"
}

unlock_luks() {
  local device=$1
  udisksctl unlock -b "$device"
}

main_menu() {
  echo -en "List Mounts\0info\x1f${cmd[lsmounts]}\n"
  echo -en "Mount\0info\x1f${cmd[mount]}\n"
  echo -en "Unmount\0info\x1f${cmd[umount]}\n"
}

select_device() {
  local prompt=$1
  list_devices | rofi -dmenu -p "$prompt"
}

select_mount() {
  local prompt=$1
  list_mounts | rofi -dmenu -p "$prompt"
}

# Main loop
# while true; do
#   choice=$(main_menu)
#   case $choice in
#   Mount)
#     device=$(select_device "Select device to mount")
#     [ -n "$device" ] && mount_device "$device"
#     ;;
#   Unmount)
#     mount_point=$(select_mount "Select mount to unmount")
#     [ -n "$mount_point" ] && unmount_device "$mount_point"
#     ;;
#   "Unlock LUKS")
#     device=$(select_device "Select LUKS device to unlock")
#     [ -n "$device" ] && unlock_luks "$device"
#     ;;
#   "List Mounts")
#     list_mounts | rofi -dmenu -p "Current Mounts"
#     ;;
#   Exit)
#     exit 0
#     ;;
#   esac
# done

# initial list
if [[ $ROFI_RETV == 0 ]]; then
  main_menu
elif [[ $ROFI_RETV == 1 ]]; then
  case $ROFI_INFO in
  "${cmd[lsmount]}")
    list_mounts
    exit 0
    ;;
  esac
fi
