[language-server]
#
# efm-langserver (linters)
#
[language-server.efm-langserver]
command = "efm-langserver"

[language-server.efm-langserver.config]
documentFormatting = true

[language-server.efm-langserver.config.languages]

[[language-server.efm-langserver.config.languages.scss]]
lintCommand = "npx --no-install stylelint --formatter unix --stdin-filename=${INPUT}"
lintStdin = true
lintFormats = [
  "%f:%l:%c: %m [%trror]",
  "%f:%l:%c: %m [%tarning]",
]

[[language-server.efm-langserver.config.languages.less]]
lintCommand = "npx --no-install stylelint --formatter unix --stdin-filename=${INPUT}"
lintStdin = true
lintFormats = [
  "%f:%l:%c: %m [%trror]",
  "%f:%l:%c: %m [%tarning]",
]

[[language-server.efm-langserver.config.languages.css]]
lintCommand = "npx --no-install stylelint --formatter unix --stdin-filename=${INPUT}"
lintStdin = true
lintFormats = [
  "%f:%l:%c: %m [%trror]",
  "%f:%l:%c: %m [%tarning]",
]

[[language-server.efm-langserver.config.languages.javascript]]
lintCommand = "npx --no-install eslint --format visualstudio --stdin --stdin-filename ${INPUT}"
lintStdin = true
lintFormats = [
  "%f(%l,%c): %trror %m",
  "%f(%l,%c): %tarning %m",
]

# [[language-server.efm-langserver.config.languages.twig]]
# lintCommand = "twigcs -r emacs ${INPUT}"
# lintStdin = true

[[language-server.efm-langserver.config.languages.php]]
lintCommand = "phpcs --report=\"emacs\" --stdin-path=${INPUT} -"
lintStdin = true
lintFormats = [
  "%f:%l:%c: %rror - %m",
  "%f:%l:%c: %tarning - %m"
]

[[language-server.efm-langserver.config.languages.bash]]
lintCommand = "shellcheck -x -fgcc -Cnever"
lintStdin = true

# [[language-server.efm-langserver.config.languages.python]]
# lintCommand = "flake8 --"
# lintStdin = true


#
# Emmet
#
[language-server.emmet-ls]
args = ["--stdio"]
command="emmet-ls"

#
# Other (defined by default)
#
[language-server.typescript-language-server]
args = ["--stdio"]
command = "typescript-language-server"
config = { provideFormatter = false }

[language-server.vscode-css-language-server]
args = ["--stdio"]
command = "vscode-css-language-server"
config = { provideFormatter = false }

[language-server.intelephense]
args = ["--stdio"]
command = "intelephense"
config = { provideFormatter = false }

[language-server.bash-language-server]
args = ["start"]
command = "bash-language-server"
config = { provideFormatter = false }

[language-server.pylsp]
command = "pylsp"
config = { provideFormatter = false }

[language-server.svelteserver]
args = ["--stdio"]
command = "svelteserver"
config = { provideFormatter = false }

#
# Language configuration
#
[[language]]
name="javascript"
auto-format=true
formatter = { command = "npx", args = ["--no-install", "prettier", "--stdin-filepath ${INPUT}", "--parser", "typescript"] }
language-servers = [
  { name = "typescript-language-server", except-features=["format"] },
  { name="efm-langserver", except-features = ["format"] },
]

[[language]]
name="css"
auto-format=true
formatter = { command = "npx", args = ["--no-install", "prettier", "--stdin-filepath ${INPUT}", "--parser", "css"] }
language-servers = [
  { name = "vscode-css-language-server", except-features=["format"] },
  { name="efm-langserver", except-features = ["format"] },
  { name = "emmet-ls" }
]

[[language]]
name="scss"
auto-format=true
formatter = { command = "npx", args = ["--no-install", "prettier", "--stdin-filepath ${INPUT}", "--parser", "scss"] }
language-servers = [
  { name = "vscode-css-language-server", except-features=["format"] },
  { name="efm-langserver", except-features = ["format"] },
  { name = "emmet-ls" }
]

[[language]]
name="less"
auto-format=true
scope = "source.scss"
injection-regex = "scss"
file-types = ["less"]
roots = []
indent = { tab-width = 2, unit = "  " }
formatter = { command = "npx", args = ["--no-install", "prettier", "--stdin-filepath ${INPUT}", "--parser", "less"] }
language-servers = [
  { name = "vscode-css-language-server", except-features=["format"] },
  { name="efm-langserver", except-features = ["format"] },
  { name = "emmet-ls" }
]

[[language]]
name="html"
auto-format=true
formatter = { command = "npx", args = ["--no-install", "prettier", "--stdin-filepath ${INPUT}", "--parser", "html"] }
language-servers = [
  { name = "vscode-html-language-server", except-features = ["format"] },
  { name = "emmet-ls" }
]

[[language]]
name="twig"
auto-format=true
formatter = { command = "npx", args = ["--no-install", "prettier", "--stdin-filepath ${INPUT}", "--parser", "melody"] }
language-servers = [
  { name = "efm-langserver", except-features = ["format"] },
  { name = "emmet-ls" }
]

[[language]]
name="vue"
auto-format=true
formatter = { command = "npx", args = ["--no-install", "prettier", "--stdin-filepath ${INPUT}", "--parser", "vue"] }

[[language]]
name="svelte"
auto-format=true
language-servers = [
  { name = "svelteserver", except-features=["format"] },
  { name = "emmet-ls" }
]
formatter = { command = "npx", args = ["--no-install", "prettier", "--stdin-filepath ${INPUT}", "--parser", "svelte"] }

[[language]]
name="php"
auto-format=false
file-types = ["php", "inc", "theme", "module", "profile"]
indent = { tab-width = 2, unit = "  " }
formatter = { command = "phpcbf", args = ["-"] }
language-servers = [
 { name = "intelephense", except-features = ["format"] },
 { name = "efm-langserver", except-features = ["format"] },
]

[[language]]
name="python"
auto-format=true
formatter = { command = "black", args = ["-"] }
language-servers = [
 { name = "pylsp", except-features = ["format"] },
 { name = "efm-langserver", except-features = ["format"] },
]

[[language]]
name = "bash"
auto-format = true
formatter = { command = "shfmt", args = ["-i", "2", "-ci", "-bn", "-sr"] }
language-servers = [
  { name="bash-language-server", except-features = ["format"] },
  { name="efm-langserver", except-features = ["format"] },
]

[[language]]
name = "yaml"
auto-format = true
formatter = { command = "npx", args = ["--no-install", "prettier", "--stdin-filepath ${INPUT}", "--parser", "yaml"] } 