#
# efm-langserver (custom linters for diagnostics)
#
[language-server.efm-langserver]
command = "efm-langserver"

# currently just for php & phpcbf
[language-server.efm-langserver.config]
documentFormatting = true

[language-server.efm-langserver.config.languages]

# stylelint
[[language-server.efm-langserver.config.languages.css]]
lintCommand = "npx --no-install stylelint --formatter unix --stdin-filename=${INPUT}"
lintStdin = true
lintFormats = [
  "%f:%l:%c: %m [%trror]",
  "%f:%l:%c: %m [%tarning]",
]

# stylelint
[[language-server.efm-langserver.config.languages.scss]]
lintCommand = "npx --no-install stylelint --formatter unix --stdin-filename=${INPUT}"
lintStdin = true
lintFormats = [
  "%f:%l:%c: %m [%trror]",
  "%f:%l:%c: %m [%tarning]",
]

# stylelint
# [[language-server.efm-langserver.config.languages.less]]
# lintCommand = "npx --no-install stylelint --formatter unix --stdin-filename=${INPUT}"
# lintStdin = true
# lintFormats = [
#   "%f:%l:%c: %m [%trror]",
#   "%f:%l:%c: %m [%tarning]",
# ]


# eslint
[[language-server.efm-langserver.config.languages.javascript]]
lintCommand = "npx --no-install eslint --format visualstudio --stdin --stdin-filename ${INPUT}"
lintStdin = true
lintFormats = [
  "%f(%l,%c): %trror %m",
  "%f(%l,%c): %tarning %m",
]

# TWIG
# [[language-server.efm-langserver.config.languages.twig]]
# lintCommand = "twigcs -r emacs ${INPUT}"
# lintStdin = true

# phpcs/phpcbf
[[language-server.efm-langserver.config.languages.php]]
# issues using helix default "format" command
formatCommand = "phpcbf -q --stdin-path=${INPUT} - || true"
formatStdin = true

lintCommand = "phpcs --report=\"emacs\" --stdin-path=${INPUT} -"
lintStdin = true
lintFormats = [
  "%f:%l:%c: %rror - %m",
  "%f:%l:%c: %tarning - %m"
]

# shellcheck
[[language-server.efm-langserver.config.languages.bash]]
lintCommand = "shellcheck -x -fgcc -Cnever"
lintStdin = true


#
# Emmet
#
[language-server.emmet-ls]
args = ["--stdio"]
command="emmet-ls"

#
# Language configuration
#
[[language]]
name="javascript"
auto-format=true
formatter = { command = "npx", args = ["--no-install", "prettier", "--stdin-filepath ${INPUT}", "--parser", "typescript"] }
language-servers = [
  { name = "typescript-language-server", except-features = ["format"] },
  # eslint
  { name = "efm-langserver", only-features = ["diagnostics"] },
]

[[language]]
name="json"
auto-format=true
formatter = { command = "npx", args = ["--no-install", "prettier", "--stdin-filepath ${INPUT}", "--parser", "json"] }
# language-servers = [
#   # eslint
#   { name = "efm-langserver", only-features = ["diagnostics"] },
# ]

[[language]]
name="css"
auto-format=true
formatter = { command = "npx", args = ["--no-install", "prettier", "--stdin-filepath ${INPUT}", "--parser", "css"] }
language-servers = [
  { name = "vscode-css-language-server", except-features=["format"] },
  # stylelint
  { name = "efm-langserver", only-features = ["diagnostics"] },
  { name = "emmet-ls", only-features = ["completion"] },
]

[[language]]
name="scss"
auto-format=true
formatter = { command = "npx", args = ["--no-install", "prettier", "--stdin-filepath ${INPUT}", "--parser", "scss"] }
language-servers = [
  { name = "vscode-css-language-server", except-features = ["format"] },
  # stylelint
  { name = "efm-langserver", except-features = ["format"] },
  { name = "emmet-ls", only-features = ["completion"] },
]

[[language]]
name="html"
auto-format=true
formatter = { command = "npx", args = ["--no-install", "prettier", "--stdin-filepath ${INPUT}", "--parser", "html"] }
language-servers = [
  { name = "vscode-html-language-server", except-features = ["format"] },
  { name = "emmet-ls", only-features = ["completion"] },
]

[[language]]
name="twig"
auto-format=true
formatter = { command = "npx", args = ["--no-install", "prettier", "--stdin-filepath ${INPUT}", "--parser", "melody"] }
language-servers = [
  # { name = "efm-langserver", only-features = ["diagnostics"] },
  { name = "emmet-ls", only-features = ["completion"] },
]

[[language]]
name="vue"
auto-format=true
formatter = { command = "npx", args = ["--no-install", "prettier", "--stdin-filepath ${INPUT}", "--parser", "vue"] }

[[language]]
name="svelte"
auto-format=true
formatter = { command = "npx", args = ["--no-install", "prettier", "--stdin-filepath ${INPUT}", "--parser", "svelte"] }
language-servers = [
  { name = "svelteserver", except-features=["format"] },
  { name = "emmet-ls", only-features = ["completion"] },
]

[[language]]
name="php"
auto-format=true
# add drupal types
file-types = ["php", "inc", "theme", "module", "profile"]
indent = { tab-width = 2, unit = "  " }
# issues using helix default "format" command
# formatter = { command = "phpcbf", args = ["-qv", "--stdin-path=${INPUT}", "-", "||", "true"] }
language-servers = [
 { name = "intelephense", except-features = ["format"] },
 # phpcs & phpcbf
 { name = "efm-langserver", only-features = ["diagnostics", "format"] },
]

# [language.debugger]
# name = "vscode-php-debug"
# transport = "stdio"
# command = "node"
# args = [ "/usr/lib/node_modules/php-debug/out/phpDebug.js" ]

# [[language.debugger.templates]]
# name = "Listen for Xdebug"
# request = "launch"
# completion = [ "ignored" ]
# args = { }
# args = { serverSourceRoot="/app/", localSourceRoot="/home/in0ni/Work/un/repos/UW2ISEEK-619/" }

[[language]]
name="python"
auto-format=true
formatter = { command = "black", args = ["-"] }
language-servers = [
 { name = "pylsp", except-features = ["format"] },
 { name = "efm-langserver", only-features = ["diagnostics"] },
]

[[language]]
name = "bash"
auto-format = true
formatter = { command = "shfmt", args = ["-i", "2", "-ci", "-bn", "-sr"] }
language-servers = [
  { name="bash-language-server", except-features = ["format"] },
  { name="efm-langserver", only-features = ["diagnostics"] },
]

[[language]]
name = "yaml"
auto-format = true
formatter = { command = "npx", args = ["--no-install", "prettier", "--stdin-filepath ${INPUT}", "--parser", "yaml"] } 
